In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import Imputer


In [2]:
## loading development data set into python 

In [3]:
df=pd.read_csv("C:\\Users\\Sumit Ranjan\\Desktop\\pgdm\\semester 5\\development_dataset.csv")

In [4]:
## Giving name to columns according to data dictionary provided by AMEX

In [5]:

new_data = df.rename(columns = {"VAR1": "ID","VAR2":"FICO","VAR3":"Business Revenue","VAR4":"TSR","VAR5":"Last 6M Avg Util","VAR6":"Income","VAR7":"Last 6M Avg Remit","VAR8":"Last 6M Avg Bal","VAR9":"Internal Revolve","VAR10":"Lending AR% in last 6M","VAR11":"ExternalBalance", "VAR12":"Months in Business" ,"VAR13":"preferred_spend_line","VAR14":"total_cards","VAR15":"preferred_bal_line", "VAR16":" preavgremit1_3_all","VAR17":"External_rev_rate", "VAR18":"Supplementary Cards","VAR19":"isChargeCust", "VAR20": "CMV","VAR21":"Assigned"
                                  }) 


In [6]:
new_data.columns

Index(['ID', 'FICO', 'Business Revenue', 'TSR', 'Last 6M Avg Util', 'Income',
       'Last 6M Avg Remit', 'Last 6M Avg Bal', 'Internal Revolve',
       'Lending AR% in last 6M', 'ExternalBalance', 'Months in Business',
       'preferred_spend_line', 'total_cards', 'preferred_bal_line',
       ' preavgremit1_3_all', 'External_rev_rate', 'Supplementary Cards',
       'isChargeCust', 'CMV', 'Assigned'],
      dtype='object')

In [7]:
## converting variable total_card to float data type

In [8]:
new_data.total_cards = new_data.total_cards.replace(to_replace='.', value = 0)

In [9]:
new_data['total_cards'] = new_data['total_cards'].astype('float')

In [10]:
## selecting data of low segment from Assignned variable 

In [11]:
new_data_2 = new_data[new_data['Assigned']=='Low']

In [12]:
new_data_2.head()

ID        FICO  Business Revenue         TSR  Last 6M Avg Util     Income  \
0   1  828.235294          0.138889  321.428571        625.911006   1.818182   
3   4  892.941177               NaN         NaN        638.076431   9.090909   
5   6  794.117647          0.117700  178.571429        624.065797  12.727273   
6   7  987.058823               NaN   35.714286        611.574748        NaN   
8   9  947.058823               NaN  821.428571        648.330121  23.636364   

   Last 6M Avg Remit  Last 6M Avg Bal  Internal Revolve  \
0           1.081550       198.113469               NaN   
3           0.820218       197.355744          4.363431   
5           0.665458       197.251700        107.066619   
6           0.970320       197.831747         22.086661   
8           0.782048       200.301604               NaN   

   Lending AR% in last 6M    ...     Months in Business  preferred_spend_line  \
0               58.632548    ...             100.083403              1.000000   
3               58.632548    ...                    NaN                   NaN   
5               58.632548    ...                    NaN              2.000000   
6                     NaN    ...                    NaN                   NaN   
8               58.632548    ...              20.016681              9.733333   

   total_cards  preferred_bal_line   preavgremit1_3_all  External_rev_rate  \
0          1.0                 1.0             1.540594                NaN   
3          1.0                 NaN             1.145729                NaN   
5          1.0                 2.0             1.037051              34.83   
6          1.0                 6.0             1.161463            1000.00   
8          1.0                11.0             1.141355            1000.00   

   Supplementary Cards  isChargeCust         CMV  Assigned  
0                    1             0  100.104991       Low  
3                    1             0  140.862306       Low  
5                    0             0  379.736661       Low  
6                    0             1  146.382100       Low  
8                    1             0   96.337349       Low  

[5 rows x 21 columns]

In [13]:
## selecting data of Medium segment from Assignned variable 

In [14]:
new_data_3 = new_data[new_data['Assigned']=='Medium']

In [15]:
## selecting data of High segment from Assignned variable 

In [16]:
new_data_4 = new_data[new_data['Assigned']=='High']

In [17]:
## Replacing missing value in each segment with "most frequent" in each segment separately

In [18]:
imputer = Imputer(missing_values="NaN", strategy="most_frequent", axis = 0)

C:\Users\Sumit Ranjan\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [19]:
imputer_1 = imputer.fit(new_data_2.drop('Assigned',axis=1))

In [20]:
new_data_2=new_data_2.drop('Assigned',axis=1)

In [21]:
new_data_2 = imputer_1.transform(new_data_2)

In [22]:
imputer_2 = imputer.fit(new_data_3.drop('Assigned',axis=1))

In [23]:
new_data_3=new_data_3.drop('Assigned',axis=1)

In [24]:
new_data_3 = imputer_2.transform(new_data_3)

In [25]:
imputer_3 = imputer.fit(new_data_4.drop('Assigned',axis=1))

In [26]:
new_data_4=new_data_4.drop('Assigned',axis=1)

In [27]:
new_data_4 = imputer_3.transform(new_data_4)

In [28]:
columns=['ID', 'FICO', 'Business Revenue', 'TSR', 'Last 6M Avg Util', 'Income',
       'Last 6M Avg Remit', 'Last 6M Avg Bal', 'Internal Revolve',
       'Lending AR% in last 6M', 'ExternalBalance', 'Months in Business',
       'preferred_spend_line', 'total_cards', 'preferred_bal_line',
       ' preavgremit1_3_all', 'External_rev_rate', 'Supplementary Cards',
       'isChargeCust', 'CMV']

In [29]:
new_data_2=pd.DataFrame(new_data_2, columns=columns)

In [30]:
new_data_2['Assigned']='Low'

In [31]:
new_data_2.head()

ID        FICO  Business Revenue         TSR  Last 6M Avg Util     Income  \
0  1.0  828.235294          0.138889  321.428571        625.911006   1.818182   
1  4.0  892.941177          0.027778   35.714286        638.076431   9.090909   
2  6.0  794.117647          0.117700  178.571429        624.065797  12.727273   
3  7.0  987.058823          0.027778   35.714286        611.574748  11.363636   
4  9.0  947.058823          0.027778  821.428571        648.330121  23.636364   

   Last 6M Avg Remit  Last 6M Avg Bal  Internal Revolve  \
0           1.081550       198.113469         22.086661   
1           0.820218       197.355744          4.363431   
2           0.665458       197.251700        107.066619   
3           0.970320       197.831747         22.086661   
4           0.782048       200.301604         22.086661   

   Lending AR% in last 6M    ...     Months in Business  preferred_spend_line  \
0               58.632548    ...             100.083403              1.000000   
1               58.632548    ...              40.033361              6.666667   
2               58.632548    ...              40.033361              2.000000   
3               58.632548    ...              40.033361              6.666667   
4               58.632548    ...              20.016681              9.733333   

   total_cards  preferred_bal_line   preavgremit1_3_all  External_rev_rate  \
0          1.0            1.000000             1.540594            1000.00   
1          1.0            6.666667             1.145729            1000.00   
2          1.0            2.000000             1.037051              34.83   
3          1.0            6.000000             1.161463            1000.00   
4          1.0           11.000000             1.141355            1000.00   

   Supplementary Cards  isChargeCust         CMV  Assigned  
0                  1.0           0.0  100.104991       Low  
1                  1.0           0.0  140.862306       Low  
2                  0.0           0.0  379.736661       Low  
3                  0.0           1.0  146.382100       Low  
4                  1.0           0.0   96.337349       Low  

[5 rows x 21 columns]

In [32]:
new_data_3=pd.DataFrame(new_data_3,columns=columns)

In [33]:
new_data_3['Assigned']='Medium'

In [34]:
new_data_4=pd.DataFrame(new_data_4,columns=columns)

In [35]:
new_data_4['Assigned']='High'

In [36]:
a=new_data_2.append(new_data_3, ignore_index = True) 

In [37]:
b=a.append(new_data_4, ignore_index = True)

In [38]:
## data with no missing value store in b 

In [39]:
b.shape

(34000, 21)

In [40]:
for col in b.columns: 
    print(col) 

ID
FICO
Business Revenue
TSR
Last 6M Avg Util
Income
Last 6M Avg Remit
Last 6M Avg Bal
Internal Revolve
Lending AR% in last 6M
ExternalBalance
Months in Business
preferred_spend_line
total_cards
preferred_bal_line
 preavgremit1_3_all
External_rev_rate
Supplementary Cards
isChargeCust
CMV
Assigned


In [41]:
b.head()

ID        FICO  Business Revenue         TSR  Last 6M Avg Util     Income  \
0  1.0  828.235294          0.138889  321.428571        625.911006   1.818182   
1  4.0  892.941177          0.027778   35.714286        638.076431   9.090909   
2  6.0  794.117647          0.117700  178.571429        624.065797  12.727273   
3  7.0  987.058823          0.027778   35.714286        611.574748  11.363636   
4  9.0  947.058823          0.027778  821.428571        648.330121  23.636364   

   Last 6M Avg Remit  Last 6M Avg Bal  Internal Revolve  \
0           1.081550       198.113469         22.086661   
1           0.820218       197.355744          4.363431   
2           0.665458       197.251700        107.066619   
3           0.970320       197.831747         22.086661   
4           0.782048       200.301604         22.086661   

   Lending AR% in last 6M    ...     Months in Business  preferred_spend_line  \
0               58.632548    ...             100.083403              1.000000   
1               58.632548    ...              40.033361              6.666667   
2               58.632548    ...              40.033361              2.000000   
3               58.632548    ...              40.033361              6.666667   
4               58.632548    ...              20.016681              9.733333   

   total_cards  preferred_bal_line   preavgremit1_3_all  External_rev_rate  \
0          1.0            1.000000             1.540594            1000.00   
1          1.0            6.666667             1.145729            1000.00   
2          1.0            2.000000             1.037051              34.83   
3          1.0            6.000000             1.161463            1000.00   
4          1.0           11.000000             1.141355            1000.00   

   Supplementary Cards  isChargeCust         CMV  Assigned  
0                  1.0           0.0  100.104991       Low  
1                  1.0           0.0  140.862306       Low  
2                  0.0           0.0  379.736661       Low  
3                  0.0           1.0  146.382100       Low  
4                  1.0           0.0   96.337349       Low  

[5 rows x 21 columns]

In [42]:
## y contain value of variable Assigned

In [43]:
y=b.Assigned

In [44]:
## x contain value of all variable except Assigned

In [45]:
x=b.drop('Assigned',axis=1)

In [46]:
## Splitting data into train and test

In [47]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 0) 

In [48]:
##  Running Xgb 

In [49]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [50]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [51]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [52]:
print(model)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)


In [53]:
y_pred = model.predict(X_test)
predictions = y_pred

In [54]:
##  Accuracy of model

In [55]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 74.48%


In [56]:
## Creating confusion matrix 

In [57]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
actual = y_test
predicted = y_pred 
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
 
print (classification_report(actual, predicted))

Confusion Matrix :
[[ 197   95  625]
 [   9 2032  959]
 [  22  459 4102]]
              precision    recall  f1-score   support

        High       0.86      0.21      0.34       917
         Low       0.79      0.68      0.73      3000
      Medium       0.72      0.90      0.80      4583

   micro avg       0.74      0.74      0.74      8500
   macro avg       0.79      0.60      0.62      8500
weighted avg       0.76      0.74      0.72      8500

